name: Trigger Chamber Sync Job

on:
    push:
      branches:
        - main  # Adjust as needed
jobs:
    trigger_sync:
        env:
            github-token: ${{ secrets.CHAMBER_API_KEY }} # Fine-grained GitHub PAT that was saved as repository secret
        if: github.event.workflow_run.conclusion == 'success'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/github-script@v6
            - name: Trigger Chamber Sync
              run: |
                await github.rest.actions.createworkflowDispatch({
                    owner: 'bobbyhiddn',
                    repo: 'Magi.Chamber',
                    workflow_id: 'fly-deploy.yml',
                    ref: 'main'
                })   